version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    versioning-strategy: "increase"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
    groups:
      cargo-dependencies:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
    groups:
      actions-dependencies:
        update-types:
          - "minor"
          - "patch"
